export * as CharacterService from './endpoints/characters'
export * as ComicsService from './endpoints/comics'
export * as CreatorsService from './endpoints/creators'
export * as EventsService from './endpoints/events'
export * as SeriesService from './endpoints/series'
export * as StoriesService from './endpoints/stories'